# Generated by Django 2.2.6 on 2019-10-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0003_auto_20191022_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationdetails',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
