# Generated by Django 2.2.6 on 2019-10-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0004_auto_20191024_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationdetails',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='', max_length=20),
        ),
    ]
